### ISSUE TITLE
Part 5: undefined manager.name in table EmployeeList

### ISSUE THREAD

**Issue by khairulpadzli** [spring-guides/tut-react-and-spring-data-rest#89] opened 2018-10-24 07:27 UTC
Hi,

I have completed part 5 of this tutorial. I have encountered an issue after login successful, the table employee is not loaded. When I debug the page, I found a javascript error where property this.props.employee.entity.manager.name is undefined in app.js

Uncaught TypeError: Cannot read property 'name' of undefined

`<td>{this.props.employee.entity.manager.name}</td>` line 462

I'm also tried the source code from github, the issue still persist.

Any solution for this? I'm new for ReactJS.

**Comment by Cellane** [comment] 2018-11-13 14:14
I hit the same issue, and after further digging into the root cause, I think it’s not a problem on the React side but rather Spring side. While the `/api/employees` route returns manager info for each employee, `/api/employees/:id` omits that info.

That being said, I unfortunately do not have any solution.

**Comment by gregturn** [comment] 2018-11-13 17:13
Okay, if this IS a caching issue, what could be done to mend this?

**Comment by Cellane** [comment] 2018-11-13 23:29
Well, I wouldn’t know since I’m just learning Spring Boot 😅 I only know that I had two browser windows, opened side by side, querying the same local server, both asking for `/api/employees/3`.

The browser window that I was previously using for other parts of the tutorial (and had thus seen the former responses of the API) was stubbornly returning only Frodo’s first name, last name and role, even after normal refresh (Cmd-R) and force refresh (Cmd-Shift-R).

The incognito window that got freshly opened just seconds ago querying the same endpoint was also returning a manager node.

**Comment by osnofa** [comment] 2019-06-15 09:40
It seems that after making the employee promises, only in chrome, they come without the manager attribute. Iv'e checked this by logging to the console and testing in different browsers:

```
	loadFromServer(pageSize) {
                ...
	        }).then(employeePromises => {
			return when.all(employeePromises);
		}).done(employees => {
			console.info(employees);
			this.setState({
				page: this.page,
				employees: employees,
				attributes: Object.keys(this.schema.properties),
				pageSize: pageSize,
				links: this.links
			});
		});
```

Does anyone know why this happens in Chrome? Can it be work without making too many changes to the code?

**Comment by osnofa** [comment] 2019-06-17 09:12
Try this: https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

**Comment by gregturn** [comment] 2019-08-08 20:49
I'm going to rule this as out of scope for the tutorial.

**Closed by gregturn** 2019-08-08 20:49 UTC
